name: WhereIs APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    env:
      ACCEPT_ANDROID_SDK_LICENSE: "yes"
      PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: "0"

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check environment
      run: |
        echo "=== SYSTEM PYTHON ==="
        python3 --version
        which python3

        echo "=== PIP ==="
        pip --version

        echo "=== BUILDOZER ==="
        buildozer --version

        echo "=== ANDROID ==="
        echo "ANDROIDAPI=$ANDROIDAPI"
        echo "ANDROIDMINAPI=$ANDROIDMINAPI"
        echo "ANDROIDNDK=$ANDROIDNDK"

    - name: Check project
      run: |
        echo "=== FILES ==="
        ls -la

        echo "=== BUILDOZER SPEC ==="
        cat buildozer.spec

        echo "=== REQUIREMENTS FILES ==="
        find . -maxdepth 3 -type f \( \
          -name "requirements.txt" -o \
          -name "pyproject.toml" -o \
          -name "setup.py" \
        \) -print

    - name: Clean build
      run: |
        rm -rf .buildozer
        rm -rf bin

    - name: Build APK
      run: |
        yes | buildozer android debug

    - name: Check APK
      run: |
        echo "=== APK ==="
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WhereIs-release-apk
        path: bin/*.apk
