name: WhereIs APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    env:
      ACCEPT_ANDROID_SDK_LICENSE: "yes"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Python
      run: |
        python3 --version
        python --version
        pip --version

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer==1.6.0
        python3 -m pip install sh

    - name: Check files
      run: |
        ls -la
        test -f buildozer.spec

    - name: Prepare build
      run: |
        chmod -R 777 .

    - name: Clean build
      run: |
        rm -rf .buildozer
        rm -rf bin

    - name: Build APK
      run: |
        yes | buildozer android debug

    - name: Check APK
      run: |
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WhereIs-release-apk
        path: bin/*.apk
